#include "Widget.h"
#include "ButtonWidget.h"
#include "MiniButtonWidget.h"
#include "WidgetApplication.h"
#include "InputWidget.h"
#include "CheckBoxWidget.h"
#include "WindowWidget.h"
#include "LabelWidget.h"
#include "FrameWidget.h"
#include "SliderWidget.h"
#include "ContainerHWidget.h"
#include "ContainerVWidget.h"
#include "DesktopWidget.h"

#include "CursorTask.h"
#include "KeyboardTask.h"
